version: '3'
services:
    dev:
        container_name: blockrock_api_dev
        image: nestjs-api-dev:1.0.0
        environment:
            NODE_ENV: development
        build:
            context: .
            dockerfile: ./Dockerfile.dev
        ports:
            - 3000:3000
        networks:
            - nestjs-network
        volumes:
            - /blockrock/node_modules
            - .:/blockrock
        restart: unless-stopped
    prod:
        container_name: blockrock_api_prod
        image: nestjs-api-prod:1.0.0
        environment:
            NODE_ENV: production
        build:
            context: .
            dockerfile: ./Dockerfile.prod
        ports:
            - 8080:8080
        networks:
            - nestjs-network
        volumes:
            - /blockrock/node_modules
            - .:/blockrock
        restart: unless-stopped
    live:
        container_name: payment_api_live
        image: nestjs-api-prod:1.0.0
        environment:
            NODE_ENV: production
        build:
            context: .
            dockerfile: ./Dockerfile
        command: yarn start:prod
        ports:
            - 8080:8080
        networks:
            - nestjs-network
        restart: unless-stopped

networks:
    nestjs-network: